  // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz0D_5Q8mZxY6Ym9RRVdzjmb9jFLQoAHk',
    appId: '1:776727685945:web:f2ef1e4602ae61a4ab56e8',
    messagingSenderId: '776727685945',
    projectId: 'motivationalquotesapp-61e8d',
    authDomain: 'motivationalquotesapp-61e8d.firebaseapp.com',
    storageBucket: 'motivationalquotesapp-61e8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqDTX1Hmiau26oqM6ZUi_l7d4c5eQKpZA',
    appId: '1:776727685945:android:27c6f4592ff9269dab56e8',
    messagingSenderId: '776727685945',
    projectId: 'motivationalquotesapp-61e8d',
    storageBucket: 'motivationalquotesapp-61e8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSBiu2nkHJHVHM_g3z0zgSc9NkQYv-H8I',
    appId: '1:776727685945:ios:38d4a29f7e435889ab56e8',
    messagingSenderId: '776727685945',
    projectId: 'motivationalquotesapp-61e8d',
    storageBucket: 'motivationalquotesapp-61e8d.appspot.com',
    iosClientId: '776727685945-63l2kla0j10aq407inoc638scrc5nss0.apps.googleusercontent.com',
    iosBundleId: 'com.example.motivationalquotesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSBiu2nkHJHVHM_g3z0zgSc9NkQYv-H8I',
    appId: '1:776727685945:ios:9a6f4770b6994dfdab56e8',
    messagingSenderId: '776727685945',
    projectId: 'motivationalquotesapp-61e8d',
    storageBucket: 'motivationalquotesapp-61e8d.appspot.com',
    iosClientId: '776727685945-ir615abadl9t3r1vpf7aik12092hqa79.apps.googleusercontent.com',
    iosBundleId: 'com.example.motivationalquotesapp.RunnerTests',
  );
}
